### PR TITLE
Fix bug in FlagSet.GetStringSlice when a comma in a string slice value

### LINKED ISSUE #81: The method FlagSet.GetStringSlice dosen't work as expected when a comma exists in a string slice
Hi,
When the flag is like this:
```
cmd --stringSlice=A,B --stringSlice=C
```
The API `FlagSet.GetStringSlice("stringSlice")` doesn't return the string array {"A,B", "C"} as expected, but {"A", "B", "C"}

### PR DESCRIPTION
**Pull request by wu8685**
fix #81

### CODE REVIEW

**Comment by wu8685** [comment]
Hi @eparis , 
Could you please help me to pass the test on go tip? I don't know how to fix it.

**Comment by smarterclayton** [comment]
Changing comma to space doesn't fix the problem - you can have spaces in flag values.

**Comment by wu8685** [comment]
I change to use `csv parser` with quotes to identify value items.

**Comment by smarterclayton** [comment]
CSV escaping is not a solution to this problem.  This behavior is surprising to a naive user, and telling them to CSV escape `command -a 'b=some,value'` is inconsistent with the vast majority of CLI's out there.

When we introduced StringSlice in pflag, we added this behavior and so a change here is not backwards compatible.  Unless we want to break *everyone* who has ever used pflag and now depends on this behavior, the only way to fix this is to

1. add a new StringSliceExact() type that doesn't look at commas and does the correct thing
2. add an extra boolean to StringSlice() that overrides using commas (which breaks downstream libraries, but does so in a way that they can react to)
3. add a boolean on the FlagSet that controls whether commas means "multiple values"

Of all of those, 1 is probably the least impactful to existing users, and gives us a migration path forward.

I am -1 to CSV escaping in any form.

**Comment by wu8685** [comment]
`FlagSet.GetStringSlice()` itself has a bug. The [unit test](https://github.com/spf13/pflag/blob/master/string_slice_test.go#L160) doesn't cover this method. When the flag is `--ss="a,b",c`, `FlagSet.GetStringSlice()` will return `"a", "b", "c"` but `"a,b", "c"`. It is confusing and uncorrect.

**Comment by wu8685** [comment]
I think it is ok to add a `StringSliceExact` type. Is it necessary to open a new issue to discuss this?

**Comment by eparis** [comment]
I don't know what clayton is talking about. He is wrong. I started looking at this and came up with https://github.com/spf13/pflag/pull/87 while i was trying to understand the report.  I'll try to get something merged today.

**Pull request merged**
