### PR TITLE
Simple suggestion for UnquoteUsage

### PR DESCRIPTION
**Pull request by t00f**
Hi guys,

Just wanted to provide a small PR to avoid printing "stringSlice" for StringSliceP params.
You already did the job for float and int. Would be nice to have if for stringSlice and maybe other types, no ?

### CODE REVIEW

**Comment by bogem** [comment]
LGTM.
Please sign a CLA.

**Comment by bogem** [comment]
@eparis

**Comment by dominicbarnes** [comment]
Can this PR be updated to use `ints` in place of `intSlice` as well?

**Comment by t00f** [comment]
Sorry for late reply. I signed the CLA and updated `ints` as requested by @dominicbarnes.

**Pull request merged**
