### PR TITLE
improve compatibility with go/flag

### PR DESCRIPTION
**Pull request by 5paceToast**
go/flag in go 1.13 has a public Output() function and a Name() function
- change out() to Output() (adjusting the rest of the file)
- add Name() and tests for it

### CODE REVIEW

**Comment by mckern** [comment]
👋 howdy! Some of this looks like it overlaps with my existing PR #220; do you want to pull my commits into your PR?

**Comment by 5paceToast** [comment]
> howdy! Some of this looks like it overlaps with my existing PR #220; do you want to pull my commits into your PR?

Absolutely!
I'm pretty extremely busy right now (unfortunate circumstances) - I'll try and get them in Wed evening, or Thu morning at the latest.
Seeing as this has been sitting here for almost 3 weeks now, I doubt that'll have much of an effect.

> Following up on this, it looks like Output has been exported for about two years now so that'd put it around Go 1.10

I'm also considering simply forking and sprucing everything up at this point, for basically the same reason.
I suspect pflag doesn't get the attention it deserves because Steve also maintains cobra and co, so it'd be nice to give it a better home :slightly_smiling_face: 
If you're interested we can try and figure something out to that effect.

**Comment by cornfeedhobo** [comment]
Re: giving pflag a better home:

the problem is that cobra doesn't expose a way to drop in another flag library ... unless you all know a trick I don't?

**Comment by 5paceToast** [comment]
> the problem is that cobra doesn't expose a way to drop in another flag library ... unless you all know a trick I don't?

I am wholly disinterested in cobra.
I am interested in pflag as it is, or at least was originally, in its time.
Wrapping around it is also of interest to me, but in a way that significantly differs from cobra.

Forks need not only exist as ways to change some "definitive upstream" pointer.
Forks can exist for the same (or quite similar) software to serve differing purposes.
If this pflag is intended to be a backend provider for cobra, so be it - I would then maintain the pflag meant for direct use.

**Comment by eparis** [comment]
I don't think cobra or viper or any of the other packages steve owns matter here. We're just busy and would love anyone who is consistently able to show good judgement and help maintain things.

In this case I'm totally fine with the changes. If @5paceToast and @mckern  agree on a PR that is correct I'll merge it.

**Comment by 5paceToast** [comment]
@mckern do you think the merged changes do you sufficient justice?

**Comment by mckern** [comment]
@5paceToast not quite; there's a test in my commit that's missing here. I took a look at your commit, and cherry-picked it onto `mckern/output`, which preserved the test for `Out()`, as well as your tests for `Name()`. I also took a turn at moving your test into its own function instead of adding it to an existing one (and [ensured you were credited as co-author on the commit for it](https://github.com/spf13/pflag/pull/220/commits)). How does that look to you?

@eparis thanks for checking in -- I know y'all are volunteers, and I appreciate your time, attention, and efforts.

**Comment by 5paceToast** [comment]
Closing in favor of #220.

**Pull request closed without merging**
