### PR TITLE
Remove require pflag v1.0.3

### LINKED ISSUE #218: v1.0.4 Has a Broken Path
edit: updated how to recreate

`go get -u github.com/golangci/golangci-lint/cmd/golangci-lint` will fail when hitting this dep

```
go get: github.com/spf13/pflag@v1.0.3 updating to
        github.com/spf13/pflag@v1.0.4: parsing go.mod:
        module declares its path as: github.com/spf13/pflags
                but was required as: github.com/spf13/pflag
```

### PR DESCRIPTION
**Pull request by cfromknecht**
Fixes #218

### CODE REVIEW

**Comment by arcticicestudio** [comment]
Would be great if this could be merged and deployed with a new patch version as soon as possible. I guess this breaks a lot of builds and CI/CD workflows for everyone who's using the `-u` flag of `go get`. The only workaround is currently to pin the version to `v1.0.2` which is not what you want.

**Comment by cfromknecht** [comment]
same here, our CI and merge pipeline are effectively frozen due to this. would be great to resolve as soon as possible without resorting to disabling all checks that depend on this package. 

@therealmitchconnors do you have a timeframe in mind?

**Comment by skyrocknroll** [comment]
We are struct on this

**Comment by smcdonald45** [comment]
Same here. Can build our projects.

**Comment by refear99** [comment]
Same here @therealmitchconnors

**Comment by umarcor** [comment]
Please, stop posting non-useful comments. You can react to any of the already existing comments, should you want to let maintainers know that this issue is relevant for you.

>  I guess this breaks a lot of builds and CI/CD workflows for everyone who's using the -u flag of go get.

I assume that anyone who is using `go get -u` either expects builds to break or is not worried about that happening. A responsible user that does not want builds to break would never use `go get -u`.

> The only workaround is currently to pin the version to v1.0.2 which is not what you want.

What' the issue with v1.0.3 or with any commit before 2019/09/05?

@cfromknecht, @skyrocknroll, @smcdonald45, @refear99, there are idiomatic ways to fix your own builds/projects independently of how long it takes to fix this or others unrelated issues in other dependencies. It'd be good for you to learn and apply those mechanism.

**Comment by cfromknecht** [comment]
> I assume that anyone who is using go get -u either expects builds to break or is not worried about that happening. A responsible user that does not want builds to break would never use go get -u.

Thanks for this tip @umarcor, indeed our build script was using `-u` which was the root cause of the issue. Will also fix this on our end to avoid situations like this in the future!

**Comment by umarcor** [comment]
> Thanks for this tip @umarcor, indeed our build script was using `-u` which was the root cause of the issue. Will also fix this on our end to avoid situations like this in the future!

Note that most CI services will allow you to mark some jobs as *allowed to fail*. Therefore, apart from fixing your main job, you can keep an additional job with `-u`. That will allow to detect issues like this fast enough, at the same time that your main build is *stable*.

**Pull request merged**
