### PR TITLE
Document AddGoFlagSet method in the README file

### LINKED ISSUE #73: Document the AddGoFlagSet method in the README file
Flags defined with Go's `flag` package can be added to the `pflag`'s flag set using the `AddGoFlagSet` method. This is necessary when using libraries that declare `flag`s, such as `glang/glog`.

It took me a while to realize that I had to add the go flagset to the pflag flag set. Developers new to this library might benefit from documentation around this.

### PR DESCRIPTION
**Pull request by alexbrand**
Added documentation to the README file to resolve #73

### CODE REVIEW

**Comment by eparis** [comment]
great, if you sign the CLA i'd love to merge.

**Comment by alexbrand** [comment]
I have gone through the signing process a couple of times. Not sure why it's not getting picked. I wonder if the check has to be kicked off again?

**Comment by eparis** [comment]
I'm not sure how this one works. Are you sure the author in the git commit is the same as how you signed it?

**Comment by alexbrand** [comment]
All set. Seems like there was some kind of issue with the email used in the commit signature.

**Pull request merged**
