### PR TITLE
Simplify algorithm of UnquoteUsage

### PR DESCRIPTION
**Pull request by bogem**
The algorithm is more readable now

### CODE REVIEW

**Comment by eparis** [comment]
I'm going to vote against this one. At the moment we just stole the code from the core golang flag library https://golang.org/src/flag/flag.go and I'd rather not have to understand any bugs we create...

**Comment by eparis** [comment]
I suggest proposing this in the core library thought!

**Comment by bogem** [comment]
There are no bugs in core library algorithm, but it's a little bit hard to understand, what does this algorithm. That's why I make easier one.

**Comment by bogem** [comment]
So?

**Comment by moorereason** [comment]
So, the stdlib explicitly avoids the `strings` library (see comment right above your edits).  Here's why:
```
BenchmarkBogemUnquoteUsage-2      3000000    409 ns/op     64 B/op    2 allocs/op
BenchmarkStdLibUnquoteUsage-2    10000000    170 ns/op     16 B/op    1 allocs/op
```
I vote No.

**Comment by bogem** [comment]
Yes, the performance is slower, but the readability is more better

**Comment by bogem** [comment]
I think the performance is higher in priority and the current method is not so unclear. So I'll close this PR

**Pull request closed without merging**
